# Config build
language: python
matrix:
  include:
    - python: 3.7.1
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
# Enabling the quiet flag can be useful if youâ€™re trying to avoid log file size limit
git:
  quiet: true
# command to run scripts
script:
  - pylint mlfinlab --rcfile=.pylintrc -f text
  - bash coverage
after_success:
  - codecov
